version: '3.7'

services:
  traefik_alola:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"       # HTTP
      - "8080:8080"   # Traefik Dashboard
    networks:
      - alola_monitoring
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    container_name: traefik_alola

  prometheus_alola:
    image: prom/prometheus:latest
    container_name: prometheus_alola
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - alola_monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`api-alola.bioinformatics.nl`) && PathPrefix(`/prometheus`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana_alola:
    image: grafana/grafana:latest
    container_name: grafana_alola
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=passwort
    networks:
      - alola_monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`api-alola.bioinformatics.nl`) && PathPrefix(`/grafana`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  alola_monitoring:

volumes:
  prometheus_data:
  grafana_data:
