global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'alola-metrics'
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true  # This allows Prometheus to scrape the target even if the certificate is self-signed
    static_configs:
      - targets: ['api-alola.bioinformatics.nl']

 
